version = 0.1
[prod.deploy.parameters]
stack_name = "brainink-api-nodejs"
resolve_s3 = true
s3_prefix = "brainink-api-nodejs"
region = "eu-west-1"
# profile = "brainink"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["BrainInkFunction=503515996770.dkr.ecr.eu-west-1.amazonaws.com/braininkapinodejs054aea3a/braininkfunction57fa4b2arepo"]
